spring:
  application:
    name: weather-api
  data:
    redis:
      client-type: lettuce
      host: "192.168.1.12"
      port: 6379
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      database: 1
      timeout: 5s
      connect-timeout: 5s
  jackson:
    deserialization:
      fail-on-unknown-properties: off


server:
  error:
    whitelabel:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs